# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.9302299  0.86019068 0.32642793]
  [0.23275933 0.01679573 0.0163154 ]
  [0.54338347 0.0285219  0.98764612]]

 [[0.2825609  0.32190453 0.80900072]
  [0.69936081 0.21514055 0.4568329 ]
  [0.33071276 0.3855032  0.82734396]]

 [[0.31025351 0.1458404  0.19496587]
  [0.32011634 0.24466475 0.24852995]
  [0.26892426 0.29259499 0.15725231]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
x = np.diag([1,2,3,4],k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
print("Checkerboard pattern with 1's and 0's:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern with 1's and 0's:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
x = np.random.random((5,5))
x = (x - np.mean(x)) / (np.std(x))

print(x)

[[ 0.02341032  0.66888611  0.43618879  0.53767548  0.19045116]
 [-0.2492326   1.1557276  -1.63814484  0.09688264  0.93468885]
 [ 0.56918302  1.34000555  0.71489078  1.58341516 -1.3707688 ]
 [-0.12719569  0.15398066  0.11375769  0.23862848 -0.12196779]
 [-2.27927148  0.3025545   0.32345844 -1.6123892  -1.98481483]]


# 5.  How to find common values between two arrays?

In [5]:
#using intersect1d function

array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 60]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40, 50, 60]
Common values between two arrays:
[10 40 60]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
#using datetime64 function

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday date: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today date: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow date: ",tomorrow)



Yesterday date:  2020-08-01
Today date:  2020-08-02
Tomorrow date:  2020-08-03


# 7. Consider two random array A and B, check if they are equal

In [7]:
x = np.random.randint(1,4,9)
y = np.random.randint(1,4,9)

print("x: ",x)
print("y: ",y)
if np.array_equal(x,y) == True:
    print("Both the arrays are equal")

else:
    print("Both the arrays are not equal")

x:  [1 1 2 3 3 3 1 3 1]
y:  [1 2 3 1 2 3 2 2 2]
Both the arrays are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
x = np.random.random(10)
print("Random vector: ",x)
print("Max value in vector: ",x.argmax())

x[x.argmax()] = 0
print("Random vector with Max value as 0: ",x)


Random vector:  [0.95012054 0.86515306 0.5692882  0.95271348 0.5749213  0.75446908
 0.15187419 0.29587576 0.70641847 0.55198809]
Max value in vector:  3
Random vector with Max value as 0:  [0.95012054 0.86515306 0.5692882  0.         0.5749213  0.75446908
 0.15187419 0.29587576 0.70641847 0.55198809]


# 9. How to print all the values of an array?

In [9]:
x = np.random.random((3,3,3))

x

array([[[0.25725524, 0.39080351, 0.5169044 ],
        [0.08563924, 0.69386898, 0.40979106],
        [0.88768911, 0.64700816, 0.14519211]],

       [[0.65908289, 0.60016323, 0.38630748],
        [0.03056859, 0.78147231, 0.82602529],
        [0.2659999 , 0.68521175, 0.36412403]],

       [[0.74849375, 0.08982107, 0.10278082],
        [0.67147518, 0.18125888, 0.05869534],
        [0.15396858, 0.4177397 , 0.37481603]]])

# 10.Subtract the mean of each row of a matrix

In [20]:
X = np.random.randint(2, 10, size = 16, dtype='l').reshape(4,4)
print(X)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[5 4 9 5]
 [5 6 3 7]
 [7 6 6 9]
 [5 3 2 4]]
[[-0.75 -1.75  3.25 -0.75]
 [-0.25  0.75 -2.25  1.75]
 [ 0.   -1.   -1.    2.  ]
 [ 1.5  -0.5  -1.5   0.5 ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [32]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

print(I)

Z += np.bincount(I, minlength=len(Z))



np.add.at(Z, I, 1)

print(Z)

[8 5 0 2 7 5 6 9 2 1 8 2 8 5 1 6 7 0 7 9]
[5. 5. 7. 1. 1. 7. 5. 7. 7. 5.]


# 12.How to get the diagonal of a dot product?

In [39]:
A = np.random.uniform(0,10,(5,5))
B = np.random.uniform(0,10,(5,5))
print("A: ", A)
print("B: ",B)

C = np.dot(A,B)

print("A.B :",C)
Diagdot =np.diag(np.dot(A, B))

print("diagonal of a dot product method 1 is....",Diagdot)


A:  [[6.985926   3.79865602 4.03950159 3.97199994 2.89266025]
 [8.07517472 9.06587092 7.59668789 7.49493311 3.73984627]
 [8.84527184 2.77545599 8.67438775 6.84125644 7.92637608]
 [2.39870201 7.0461711  7.31314925 4.14268884 0.41609017]
 [4.30967778 9.36116309 4.5316149  7.58270759 3.73714684]]
B:  [[7.01805997 4.40696266 0.04849416 3.52744492 3.30074576]
 [2.18289517 4.18915775 7.31154192 1.25391137 1.02351003]
 [4.64365184 8.93391602 2.48504788 8.3512244  4.72010269]
 [0.72044039 0.31821441 5.40380588 4.49139589 9.38831559]
 [6.37059113 9.35850505 7.52400048 3.64292976 9.28384759]]
A.B : [[ 97.36729938 111.12337553  81.37945791  91.51801371 110.15899636]
 [140.96296395 178.81789445 154.19499588 150.58088693 176.87521562]
 [163.84043285 204.4598743  138.8849548  166.72516594 210.79584341]
 [ 71.81030702 110.63581887  95.32517331  98.49255658  92.40393563]
 [100.99397994 136.08007927 149.00858498 112.45585785 151.08003615]]
diagonal of a dot product method 1 is.... [ 97.36729938 178.817

# 13.How to find the most frequent value in an array?

In [40]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[1 4 4 6 6 3 7 4 6 9 0 3 1 2 4 3 3 8 0 8 7 7 2 3 1 8 9 8 0 2 4 9 3 9 1 3 7
 4 3 5 5 1 8 1 7 7 2 1 5 8]
3


# 14.How to get the n largest values of an array

In [47]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 10


print (Z[np.argsort(Z)[-n:]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [54]:
Z = np.array([("karthik", 5.6, 1),
              ("Messi", 4.6, 2)])
R = np.core.records.fromarrays(Z.T,names='Name, Value, Rank',formats = 'S8, f8, i8')
print(R)

[(b'karthik', 5.6, 1) (b'Messi', 4.6, 2)]
